### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erwin-kok**
Added `multibase` part of Kotlin project `multiformat`

### CODE REVIEW

**Review by vmx — COMMENTED** [review]
So far this list contains one implementation per language. Now we have two for Kotlin. I think it would make sense to do it similarly to https://github.com/multiformats/multihash where we then list all implementations of a single language.

I.e. something like:

 - Kotlin
   - [kotlin-multibase](https://github.com/changjiashuai/kotlin-multibase)
   - `multibase` part of Kotlin project [multiformat](https://github.com/erwin-kok/multiformat)

**Comment by erwin-kok** [comment]
Thanks for reviewing!
Agreed, its better to have one language. One moment I'll correct this.

**Comment by erwin-kok** [comment]
Update to README.md. Please have another look whenever suits you.
Thanks!

**Review by vmx — APPROVED** [review]
Thanks!

**Pull request merged**
