### PR TITLE
Add reserved code `/`

### PR DESCRIPTION
**Pull request by ben221199**
The code `/` is used by multiaddr, so it seems reasonable to me to reserve this character.

For example, if there could be a data structure like this:
```json
{
	"address": "<value>"
}
```

The `<value>` could be:
 - `QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N`
 - `12D3KooWD3eckifWpRn9wQpMG9R9hX3sD158z7EqHWmweQAJU5SA`
 - `bafzaajaiaejcal72gwuz2or47oyxxn6b3rkwdmmkrxgkjxzy3rqt5kczyn7lcm3l`

But this could maybe also the value:
 - `/ipfs/QmYyQSo1c1Ym7orWxLYvCrM2EmxFTANf8wXmmE7DWjhx5N`

### CODE REVIEW

**Comment by rvagg** [comment]
yeah, this might not be a terrible idea, at least so we have a prompt to consider carefully if we ever want to add a `/` multibase prefix.

@mxinden @marten-seemann any objections or input?

**Comment by mxinden** [comment]
> @mxinden @marten-seemann any objections or input?

No objections from my end. Maybe @lidel has thoughts on this.

**Comment by ben221199** [comment]
I think https://github.com/multiformats/multiformats/issues/63 is also relevant here in some way.

**Comment by marten-seemann** [comment]
No objections, but I don't feel confident enough to give an approval.

**Comment by ben221199** [comment]
What can I do to make it confident enough for an approval?

**Review by rvagg — APPROVED** [review]
no harm in reserving it, it'll save potential future pain if we _accidentally_ allocate a multibase with `/` that's not related to multiaddr, and if we decide somehow to add one then we can undo the reservation but it'd be an intentional thing

**Pull request merged**
